version: '3'
services:
  dbpostgres:
    image: postgres:13
    ports:
    - "5432:5432"
    volumes:
    - "db_postgres:/var/lib/postgresql/data"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: 123456

  dbclient:
    image: dpage/pgadmin4
    depends_on:
      - dbpostgres
    ports:
    - 443:443
    - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin


volumes:
  db_postgres:


